### ISSUE TITLE
Incompatible with darwin_arm64

### ISSUE THREAD

**Issue by hexedpackets** [terraform-google-modules/terraform-google-container-vm#112]
### TL;DR

The usage of the deprecated `template` provider makes this module unusable with newer MacBooks running ARM64. HashiCorp has stated that the template provider [should be replaced with the templatefile function](https://github.com/hashicorp/terraform/issues/30055) and they won't be publishing updated binaries for the provider.

### Observed behavior

Attempting to run `terraform init` with this module configured returns the following error:

```
╷
│ Error: Incompatible provider version
│ 
│ Provider registry.terraform.io/hashicorp/template v2.2.0 does not have a
│ package available for your current platform, darwin_arm64.
│ 
```

### Terraform Configuration

```hcl
module "gce_test" {
  source                = "terraform-google-modules/container-vm/google//modules/cos-generic"
  version               = "3.1.0"
  instance_count        = "1"
  instance_type         = "n2-standard-4"
  project_id            = module.gce_test_project.project_id
  region                = "us-east1"
  zone                  = "us-east1-b"
  vm_tags               = ["ssh"]
  reserve_ip            = true
  cloud_init            = "cloud-config.yaml"
}
```
```


### Terraform Version

```sh
Terraform v1.4.6
```

**Comment by lex-divert** [comment]
This module is my last upstream dependency that still uses the `template` provider, which has been deprecated since before the Terraform 1.0 release. My hope is that by bumping it one of the existing contributors will notice, but I'm guessing it might fall to one of us end-users to make time to submit a PR.

FTR: when I need to execute Terraform on my MacOS workstation, I've been working around the problem by wrapping calls inside `docker run --platform linux/amd64`. It's awkward, but (so far) not annoying enough to make me find a better solution.
