### ISSUE TITLE
Update MIG example to use Terraform v0.12 compatible modules

### ISSUE THREAD

**Issue by aaron-lane** [terraform-google-modules/terraform-google-container-vm#28]

**Comment by ivankorn** [comment]
`terraform validate` fails on that: [output](https://github.com/terraform-google-modules/terraform-google-container-vm/issues/32#issuecomment-521247483)
#32

**Comment by ivankorn** [comment]
This issue is blocked by 0.12 support for following 2 modules:
- [`terraform-google-managed-instance-group`](https://github.com/GoogleCloudPlatform/terraform-google-managed-instance-group/issues/42)
- [`terraform-google-lb-http`](https://github.com/GoogleCloudPlatform/terraform-google-lb-http/issues/51)

**Comment by morgante** [comment]
@ivankorn You can replace the MIG with this module: https://github.com/terraform-google-modules/terraform-google-vm/tree/master/modules/mig

**Comment by ivankorn** [comment]
Great! Thank you, @morgante !

**Comment by captain-kark** [comment]
This is still reported as a ["Known Issue" in the readme file](https://github.com/terraform-google-modules/terraform-google-container-vm#known-limitations).

**Comment by uhinze** [comment]
Also it looks like 0.10 is the [only supported version](https://github.com/terraform-google-modules/terraform-google-container-vm#requirements), could be changed while at it.
