### ISSUE TITLE
Remove dependency on ruby

### ISSUE THREAD

**Issue by mxk** [terraform-google-modules/terraform-google-container-vm#33]
The dependency on ruby creates extra complexity for using this module. It looks like ruby is being used to convert JSON data into YAML. Can the built-in `yamlencode` function be used for this instead?

**Comment by morgante** [comment]
Yes, I think we could explore using `yamlencode` instead. PRs welcome.

**Comment by anantasty** [comment]
The use of yaml encode is still experimental. It converts boolean false to "false" which is undesired behavior.
Output from the tests is attached below:

```
     expected: {"spec"=>{"containers"=>[{"env"=>[{"name"=>"TEST_VAR", "value"=>"Hello World!"}], "image"=>"gcr.io/go...fs-0"}, {"gcePersistentDisk"=>{"fsType"=>"ext4", "pdName"=>"data-disk-0"}, "name"=>"data-disk-0"}]}}
          got: {"spec"=>{"containers"=>[{"env"=>[{"name"=>"TEST_VAR", "value"=>"Hello World!"}], "image"=>"gcr.io/go...fs-0"}, {"gcePersistentDisk"=>{"fsType"=>"ext4", "pdName"=>"data-disk-0"}, "name"=>"data-disk-0"}]}}

     (compared using ==)

     Diff:
     @@ -1,2 +1,2 @@
     -"spec" => {"containers"=>[{"env"=>[{"name"=>"TEST_VAR", "value"=>"Hello World!"}], "image"=>"gcr.io/google-samples/hello-app:1.0", "volumeMounts"=>[{"mountPath"=>"/cache", "name"=>"tempfs-0", "readOnly"=>false}, {"mountPath"=>"/persistent-data", "name"=>"data-disk-0", "readOnly"=>false}]}], "restartPolicy"=>"Always", "volumes"=>[{"emptyDir"=>{"medium"=>"Memory"}, "name"=>"tempfs-0"}, {"gcePersistentDisk"=>{"fsType"=>"ext4", "pdName"=>"data-disk-0"}, "name"=>"data-disk-0"}]},
     +"spec" => {"containers"=>[{"env"=>[{"name"=>"TEST_VAR", "value"=>"Hello World!"}], "image"=>"gcr.io/google-samples/hello-app:1.0", "volumeMounts"=>[{"mountPath"=>"/cache", "name"=>"tempfs-0", "readOnly"=>"false"}, {"mountPath"=>"/persistent-data", "name"=>"data-disk-0", "readOnly"=>"false"}]}], "restartPolicy"=>"Always", "volumes"=>[{"emptyDir"=>{"medium"=>"Memory"}, "name"=>"tempfs-0"}, {"gcePersistentDisk"=>{"fsType"=>"ext4", "pdName"=>"data-disk-0"}, "name"=>"data-disk-0"}]},
```

**Comment by morgante** [comment]
Can we link/file an upstream issue?

**Comment by Tho77** [comment]
This is an unfortunate dependency as I'm running Terraform from inside Google Cloud Build and can't find an easy way to get Ruby installed.

**Comment by taylorludwig** [comment]
I started this in PR #57 

Terraform's `yamlencode` does work but there are a couple migration issues. 

**1. `yamlencode` does convert bools just fine.** 

Problem is in the previous examples we explicitly set them as strings `readOnly  = "false"` and then the ruby code forced them back to bools 

https://github.com/terraform-google-modules/terraform-google-container-vm/blob/master/helpers/map_to_yaml.rb#L19

Now that we are on 0.12 we can set them properly to bools (`false` instead of `"false"`) and let `yamlencode` convert them correctly. 

The previous way would have actually introduced other bugs. Say you wanted an env var of `"true"` as a string. Ruby helper would have converted this to a yaml bool and the env var would have been invalid. 

Downside to converting now is we need users of this module to convert their container input var to switch any string wrapped bools to proper bools. Leaving the volume as `readOnly  = "false"`, while valid yaml, will result in invalid container definition and the container wouldn't come up. 

**2. `yamlencode` results in string wrapped keys**

If you look at the resulting yaml it'll look something like this 

```yaml
 "gce-container-declaration" = <<~EOT
    "spec":
        "containers":
           - "env":
               - "name": "TEST_VAR"
                  "value": "Hello World!"
```
You'll notice all the keys are wrapped in strings. The ruby helper didn't do this.  It would have been

```yaml
 "gce-container-declaration" = <<~EOT
    spec:
        containers:
           - env:
               - name: "TEST_VAR"
                  value: "Hello World!"
```

Wrapped keys are valid yaml, and the containers come up just fine - problem is that if people upgrade to the new module version terraform will show resource metadata updates, even though the resulting container that is created won't be any different. 

If you look at the PR you'll see tests don't need to be updated because the `gcp.rb` controls. Perform a ruby `YAML.load` so the resulting ruby map is the same with or without wrapped key names.

**Comment by morgante** [comment]
Ok those all sound like acceptable tradeoffs. We can increment a major version just to be safe.
